/*Copyright (c) 2011-2012 Moat Inc. All Rights Reserved.*/
try{(function(){function Q(){for(var b=0;b<x.length;b++){var k;a:{k=["focusin","focusout","blur","focus","scroll"];for(var a=0;a<k.length;a++)if(x[b].evt==k[a]){k=!0;break a}k=!1}k||n.c.b(x[b].obj,x[b].evt,x[b].cb)}for(b=0;b<C.length;b++)window.clearTimeout(C[b]);for(b=0;b<D.length;b++)window.clearInterval(D[b])}var n={};(function(b){b.a={};b.a.a=function(){var k=b.a.b();return 5===k||6===k||7===k};b.a.b=function(){if("Microsoft Internet Explorer"===navigator.appName){var b=/MSIE ([0-9]{1,}[.0-9]{0,})/;
null!==b.exec(navigator.userAgent)&&(b=parseFloat(RegExp.$1));return b}return null};b.a.c=function(b){return new Date-b.de};b.a.d=function(){return null!==/iPad|iPhone|iPod|Silk|Kindle|Android|BlackBerry|PlayBook|Windows Phone/.exec(navigator.userAgent)};b.a.e=function(){var b=window;try{return"undefined"!==typeof b.external&&"undefined"!==typeof b.external.InPrivateFilteringEnabled&&b.external.InPrivateFilteringEnabled()||"undefined"!==typeof b.external&&"undefined"!==typeof b.external.msTrackingProtectionEnabled&&
b.external.msTrackingProtectionEnabled()||"undefined"!==typeof b._gaUserPrefs&&b._gaUserPrefs.ioo&&b._gaUserPrefs.ioo()||"undefined"!==typeof navigator.doNotTrack&&("yes"===navigator.doNotTrack||!0===navigator.doNotTrack)||"undefined"!==typeof b._gaUserPrefs&&!0===b._gaUserPrefs}catch(a){return!1}};b.a.f=function(){var b;try{b=document.location.protocol}catch(a){b=document.createElement("a"),b.href="",b=b.protocol}return"https:"===b}})(n);(function(b){b.b={};b.b.a="MoatSuperV2";b.b.b=1;b.b.c=-1!==
navigator.userAgent.toLowerCase().indexOf("firefox")})(n);(function(b){function k(b){return function(){var a=!1;return function(e){try{b(e)}catch(h){if(!a){a=!0;e=h.name+" in callback: "+h.message+", stack="+h.stack;try{var i="http://v3.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("FORBESINREDHEADER1")+"&ac=1&k="+escape(e)+"&ar="+escape("f03d6f3-clean")+"&j="+escape(document.referrer)+"&cs="+(new Date).getTime();(new Image(1,1)).src=i}catch(m){}}}}}()}b.c={};var a={};b.c.a=
function(b,d,e,h){e=k(e);b.addEventListener?b.addEventListener(d,e,!1):b.attachEvent("on"+d,e);x.push({obj:b,evt:d,cb:e});h&&(a[d+h]=e)};b.c.b=function(b,d,e,h){e=h?a[d+h]:e;b.removeEventListener?b.removeEventListener(d,e,!1):b.detachEvent("on"+d,e)};b.c.c=function(b,a){var b=k(b),e=setInterval(b,a);D.push(e);return e};b.c.d=function(b,a){var b=k(b),e=setTimeout(b,a);C.push(e);return e};b.c.e=function(b,a,e){for(var h=[],i=3;i<arguments.length;i++)h.push(arguments[i]);var m=0,l=function(){m+=1;!0!==
b.apply(this,h)&&m<a&&setSafeTimeout(l,e)};l()}})(n);(function(b){function k(b,f,a){b.IR5.MIN[a]=Math.min(f,b.IR5.MIN[a])||f||1;b.IR5.MAX[a]=Math.max(f,b.IR5.MAX[a])||f}function a(b,f){f.be=Math.max("undefined"!==typeof f.be?f.be:0,b-f.bf);"undefined"===typeof f.by&&f.be>=n&&(f.by=f.bk)}function c(a){a.az===b.d.a.d.a?a.az=b.d.a.d.b:a.az===b.d.a.d.b&&(a.az=b.d.a.d.a)}function d(a){a.ba===b.d.a.d.a?a.ba=b.d.a.d.b:a.ba===b.d.a.d.b&&(a.ba=b.d.a.d.a)}function e(a){a.ax===b.d.a.b.a?a.ax=b.d.a.b.b:a.ax===
b.d.a.b.b&&(a.ax=b.d.a.b.a)}function h(a){a.ay===b.d.a.c.a?a.ay=b.d.a.c.b:a.ay===b.d.a.c.b&&(a.ay=b.d.a.c.a)}function i(b,a){"undefined"===typeof a.bk&&(a.bk=0);a.bk+=b-a.bo;a.bo=b}function m(b,a){"undefined"===typeof a.bl&&(a.bl=0);a.bl+=b-a.bp;a.bp=b}function l(b,a){"undefined"===typeof a.bg&&(a.bg=0);"undefined"===typeof a.bc&&(a.bc=0);a.bu=b-a.bs;a.bu>a.bc&&(a.bc=a.bu);a.bg+=b-a.bq;a.bc>=s&&"undefined"===typeof a.bw&&(a.bk+=b-a.bo,a.bw=a.bk);a.bq=b}function g(b,a){"undefined"===typeof a.bh&&(a.bh=
0);"undefined"===typeof a.bd&&(a.bd=0);a.bv=b-a.bt;a.bv>a.bd&&(a.bd=a.bv);a.bh+=b-a.br;a.bd>=s&&"undefined"===typeof a.bx&&(a.bl+=b-a.bp,a.bx=a.bl);a.br=b}b.d={};var j=500,r=3E3,s=500,n=500;b.d.a={};b.d.a.a={};b.d.a.a.a=0;b.d.a.a.b=1;b.d.a.b={};b.d.a.b.a=0;b.d.a.b.b=1;b.d.a.c={};b.d.a.c.a=0;b.d.a.c.b=1;b.d.a.d={};b.d.a.d.a=0;b.d.a.d.b=1;b.d.a.e={};b.d.a.e.a=0;b.d.a.e.b=1;b.d.a.f={};b.d.a.f.a=0;b.d.a.f.b=1;b.d.a.f.c=2;b.d.b=function(b){k(b,b.aj,"x");k(b,b.ak,"y");b.IR5.AREA=(b.IR5.MAX.x-b.IR5.MIN.x)*
(b.IR5.MAX.y-b.IR5.MIN.y)};b.d.c=function(a){function f(){if((new Date).getTime()-E>=j){b.d.d({type:"park"},a);var f={e:15};f.q=a.aq[15]++;f.x=a.aj;f.y=a.ak;b.e.a(a,f);clearInterval(h);a.au=b.d.a.a.a}}var c=a.au;if(c===b.d.a.a.a){E=(new Date).getTime();var h=b.c.c(f,50);a.au=b.d.a.a.b}else c===b.d.a.a.b&&(E=(new Date).getTime())};b.d.e=function(a){function f(){if((new Date).getTime()-F>=r){b.d.f({type:"park"},a);var f={e:15};f.q=a.aq[15]++;f.x=a.aj;f.y=a.ak;b.e.a(a,f);clearInterval(h);a.av=b.d.a.a.a}}
var c=a.av;if(c===b.d.a.a.a){F=(new Date).getTime();var h=b.c.c(f,50);a.av=b.d.a.a.b}else c===b.d.a.a.b&&(F=(new Date).getTime())};b.d.g=function(a,f){var h=a.type;if(f.az===b.d.a.d.a){if("mouseover"===h||"mousemove"===h)f.bo=(new Date).getTime(),c(f)}else if(f.az===b.d.a.d.b){"mousemove"===h&&i((new Date).getTime(),f);if("mouseout"===h||"blur"===h)i((new Date).getTime(),f),c(f);"scooper"===h&&i((new Date).getTime(),f)}};b.d.h=function(a,f){var c=a.type;if(f.ba===b.d.a.d.a){if("mouseover"===c||"mousemove"===
c)f.bp=(new Date).getTime(),d(f)}else if(f.ba===b.d.a.d.b){"mousemove"===c&&m((new Date).getTime(),f);if("mouseout"===c||"blur"===c)m((new Date).getTime(),f),d(f);"scooper"===c&&m((new Date).getTime(),f)}};b.d.d=function(a,f){if(2!=f.an){var c=a.type;if(f.ax===b.d.a.b.a){if("mouseover"===c||"mousemove"===c)f.bq=(new Date).getTime(),f.bs=(new Date).getTime(),e(f)}else f.ax===b.d.a.b.b&&(("mousemove"===c||"mouseout"===c)&&l((new Date).getTime(),f),"park"===c&&l((new Date).getTime()-j,f),("mouseout"===
c||"park"===c)&&e(f))}};b.d.f=function(a,f){if(2!=f.an){var c=a.type;if(f.ay===b.d.a.c.a){if("mouseover"===c||"mousemove"===c)f.br=(new Date).getTime(),f.bt=(new Date).getTime(),h(f)}else f.ay===b.d.a.c.b&&(("mousemove"===c||"mouseout"===c)&&g((new Date).getTime(),f),"park"===c&&g((new Date).getTime()-r,f),("mouseout"===c||"park"===c)&&h(f))}};b.d.i=function(c,f){var h=c.type;if(f.bb==b.d.a.e.a){if("mouseover"==h||"mousemove"==h)f.bf=(new Date).getTime(),f.bb=b.d.a.e.b}else f.bb==b.d.a.e.b&&("mouseout"==
h?(a((new Date).getTime(),f),f.bb=b.d.a.e.a):("mousemove"==h||"scooper"==h)&&a((new Date).getTime(),f))}})(n);(function(b){function k(a){var a=a||window.event,f=r(a.target||a.srcElement);if(f){g(f,a);if((f.aj!==f.al||f.ak!==f.am)&&0<=f.aj&&f.aj<=parseInt(f.aa.offsetWidth)&&0<=f.ak&&f.ak<=parseInt(f.aa.offsetHeight)&&!w)b.d.d(a,f),b.d.f(a,f),b.d.g(a,f),b.d.i(a,f),b.d.h(a,f),b.d.b(f),b.d.c(f),b.d.e(f),0===f.ar.length&&(f.ai=s(f)),f.ar.push(f.aj),f.as.push(f.ak),f.at.push(b.a.c(f)),f.al=f.aj,f.am=f.ak;
f.ai!==s(f)&&1<f.ar.length&&j(f,"onMouseMove");return{x:f.aj,y:f.ak}}}function a(a){var a=a||window.event,f=r(a.target||a.srcElement);if(f&&(g(f,a),a={e:2},a.q=f.aq[2]++,a.x=f.aj,a.y=f.ak,b.e.a(f,a),0===f.an)){var c=f.aj,h=f.ak;o.v&&b.c.d(function(){if(!o.v){var a={e:3};a.q=f.aq[3]++;a.x=c;a.y=h;b.e.a(f,a)}},1E3)}}function c(a){for(var f={},c=0;c<a.changedTouches.length;c+=1){var h=r(a.changedTouches[c].target||a.changedTouches[c].srcElement);if(h){g(h,a.changedTouches[c]);f.e=23;f.q=h.aq[23]++;f.x=
h.aj;f.y=h.ak;var i=f;var d=h;now=(new Date).getTime();"undefined"===typeof d.ct?d.ct=now:(interval=now-d.ct,d.ct=now,d.cu=Math.min(d.cu,interval)||interval);i.bz=void 0;b.e.a(h,f)}}}function d(a,c,i){if(2==a.an){var d=c.e,g=a.ck;g==b.d.a.f.a&&6===d?(e(a,0),a.cl=b.a.c(a),a.ck=b.d.a.f.b):g==b.d.a.f.b?22===d?(h(a,c),e(a,i),a.cl=b.a.c(a)):7===d&&(1E3<b.a.c(a)-a.cl?(clearTimeout(a.cm),c.e=22,h(a,c),a.cn=0,a.ck=b.d.a.f.a):a.ck=b.d.a.f.c):g==b.d.a.f.c&&(6==d?(1E3<b.a.c(a)-a.cl&&(clearTimeout(a.cm),a.cn=
0,a.cl=b.a.c(a),e(a,0)),a.ck=b.d.a.f.b):22==d&&(h(a,c),a.ck=b.d.a.f.a,a.cn=0))}}function e(a,c){var h=5>a.cn?1E3:2*c,i={e:22};a.cm=b.c.d(function(){d(a,i,h)},h)}function h(a,c){c.q=a.aq[c.e]++;c.m=b.a.c(a);a.cl=c.m;b.e.a(a,c);a.cn++}function i(a){var a=a||window.event,c=r(a.target||a.srcElement);if(c){b.d.d(a,c);b.d.f(a,c);b.d.g(a,c);b.d.i(a,c);b.d.h(a,c);g(c,a);a={e:6};a.q=c.aq[6]++;a.x=0>c.aj?0:c.aj;a.y=0>c.ak?0:c.ak;var h=b.a.c(c);a.m=h;b.e.a(c,a);d(c,a,0)}}function m(a){var a=a||window.event,
c=r(a.target||a.srcElement);c&&(b.d.d(a,c),b.d.f(a,c),b.d.g(a,c),b.d.i(a,c),b.d.h(a,c),g(c,a),a={e:7},a.q=c.aq[7]++,a.x=0>c.aj?0:c.aj,a.y=0>c.ak?0:c.ak,b.e.a(c,a),d(c,a,0))}function l(a){var a=a||window.event,c=r(a.target||a.srcElement);c&&0!==c.an&&(g(c,a),a={e:3},a.q=c.aq[3]++,a.x=c.aj,a.y=c.ak,b.e.a(c,a))}function g(a,c){var h,i;a.dm||(a.cb=a.dz,a.dm=1);var d;"undefined"!==typeof c.pageX?(h=c.pageX,i=c.pageY):(h=(c.target||c.srcElement).ownerDocument||document,i=h.documentElement,d=h.body,h=c.clientX+
(i&&i.scrollLeft||d&&d.scrollLeft||0)-(i&&i.clientLeft||d&&d.clientLeft||0),i=c.clientY+(i&&i.scrollTop||d&&d.scrollTop||0)-(i&&i.clientTop||d&&d.clientTop||0));for(var g=a.aa,m=0,l=d=0;l<y;l++)if(g){m+=g.offsetLeft;if(!b.b.c||!("TABLE"===g.tagName&&"inline"===g.style.display))d+=g.offsetTop;g=g.offsetParent}else break;h-=m;i-=d;a.aj=parseInt(h,10);a.ak=parseInt(i,10)}function j(a){a.ai=s(a);var c={e:1};c.q=a.aq[1]++;c.x=a.ar.join("a");c.y=a.as.join("a");for(var h=b.a.c(a),i=a.at,d=[],g=0;g<i.length;g++)isNaN(i[g])||
d.push(Math.abs(i[g]-h));c.c=d.join("a");c.m=h;b.e.a(a,c);a.ar=[];a.as=[];a.at=[]}function r(a){var b;if("undefined"!==typeof a[v])return p[a[v]];if("OBJECT"===a.tagName)for(var c=0;c<a.children.length;c++)if(b=a.children[c],"undefined"!==typeof b&&"EMBED"===b.tagName&&"undefined"!==typeof b[v])return p[b[v]];for(c=0;c<y;c++)if(a.parentNode){if(a=a.parentNode,"undefined"!==typeof a[v])return p[a[v]]}else break;return null}function s(a){return Math.floor(b.a.c(a)/n)}b.f={};var n=1E3;b.f.a=function(h){b.c.a(h,
"click",l,!1);b.c.a(h,"mousedown",a,!1);w?b.c.a(h,"touchstart",c,!1):(b.c.a(h,"mousemove",k,!1),b.c.a(h,"mouseover",i,!1),b.c.a(h,"mouseout",m,!1))};b.f.b=function(){for(var a in p)if(p.hasOwnProperty(a)){var c=p[a];c&&(b.d.g({type:"scooper"},c),b.d.i({type:"scooper"},c),b.d.h({type:"scooper"},c),1<c.ar.length&&c.ai!==s(c)&&j(c,"scooper"))}}})(n);(function(b){function k(a,c,d,e,h){if(0!==c.indexOf("http:")&&0!==c.indexOf("https:"))if("/"===c[0])c=window.location.protocol+"//"+window.location.host+
c;else var i=window.location.pathname.split("/").slice(0,-1).join("/"),c=window.location.protocol+"//"+window.location.host+"/"+i+(i?"/":"")+c;"IFRAME"!==a.tagName&&(c=c.split("?")[0]);this.zr=o.zr;o.zr++;p[this.zr]=this;a[v]=this.zr;a[t]=!0;"undefined"===typeof d&&(d=!1);"undefined"===typeof e&&(e={});o.i[G]=!0;this.aa=a;this.ee={};a:{i=this.aa.parentNode;if(H)i=b.i.a(i);else if(1===b.b.b)var m=b.h.b(this.aa),m=b.h.c(this.aa,m),i=m[m.length-1]||i;for(m=0;m<y;m++)if(i){if("forbes_modal_window"===
i.id){i=!0;break a}i=i.parentNode}else break;i=!1}this.dw=i;this.ae=c;this.ag=e;this.ah=void 0;this.ai=0;this.an=this.am=this.al=this.ak=this.aj=void 0;this.ao=h;this.ap=d;this.ar=[];this.as=[];this.at=[];this.av=this.au=b.d.a.a.a;this.ax=b.d.a.b.a;this.ay=b.d.a.c.a;this.ba=this.az=b.d.a.d.a;this.bb=b.d.a.e.a;this.by=this.bx=this.bw=this.bv=this.bu=this.bt=this.bs=this.br=this.bq=this.bp=this.bo=this.bm=this.bl=this.bk=this.bi=this.bh=this.bg=this.bf=this.be=this.bd=this.bc=void 0;this.ca=this.bz=
!1;this.cb=this.cu=this.ct=void 0;this.cc={};this.cl=this.cm=this.cw=void 0;this.cn=0;this.ck=b.d.a.f.a;this.cd=!1;this.cy=void 0;this.dt=!1;this.db=void 0;this.ce=!1;this.ef=b.h.d(this);this.cf=!1;this.af=Number(this.ef);this.ds=this.ch=this.dr=this.cg=0;this.dq=this.bn=void 0;this.IR5={MIN:{x:void 0,y:void 0},MAX:{x:void 0,y:void 0},AREA:0};this.dx=this.dz=this.dy=this.ea=this.dm=0;this.KILLED=this.dd=!1;this.aq={};this.aq.g=0;this.aq[1]=0;this.aq[2]=0;this.aq[3]=0;this.aq[13]=0;this.aq[0]=0;this.aq[4]=
0;this.aq[5]=0;this.aq[6]=0;this.aq[7]=0;this.aq[9]=0;this.aq[8]=0;this.aq[15]=0;this.aq[16]=0;this.aq[21]=0;this.aq[22]=0;this.aq[23]=0;this.an="IFRAME"===a.tagName?2:"IMG"===a.tagName?1:"EMBED"===a.tagName||"OBJECT"===a.tagName?0:3;b.g.b(this)}b.g={};b.g.a=function(a,c,d,e,h,i){return i?(c=+new Date,p[i.zr]=i,a[v]=i.zr,a[t]=!0,i.aa=a,i.df=c,i.dg=c,b.f.a(i.aa),a={e:0},a.q=i.aq[0]++,b.e.a(i,a),b.h.a(i),i):new k(a,c,d,e,h)};b.g.b=function(a){a.de=a.ao.startTime;var c=(new Date).getTime();a.df=c;a.dg=
c;a.dd=!0;c={e:0};c.q=a.aq[0]++;b.e.a(a,c);b.f.a(a.aa);b.h.a(a)}})(n);(function(b){b.j={};b.j.a=function(b,a){var c;a.outerHTML?c=a.outerHTML:(c=document.createElement("div"),c.appendChild(a.cloneNode(!0)),c=c.innerHTML);c=[/flashvars\s*=\s*(".*?"|'.*?')/i.exec(c),/name\s*=\s*["']flashvars["']\s*value\s*=\s*(".*?"|'.*?')/i.exec(c),/value\s*=\s*(".*?"|'.*?')\s*name\s*=\s*["']flashvars["']/i.exec(c),b];for(var d,e,h={},i=0;i<c.length;i++){if((d=c[i])&&"object"===typeof d&&d[1])d=d[1].replace(/&amp;/g,
"&").replace(/&quot;/g,'"').replace(/^"/g,"").replace(/"$/g,"").replace(/^'/g,"").replace(/'$/g,"");else if("string"===typeof d)d=d.split("?")[1];else continue;if(d){d=d.split("&");for(var m=0;m<d.length;m++)e=d[m].split("="),2>e.length||"function"==e[0].slice(0,8)||(h[e[0]]=[e[1]])}}return h}})(n);(function(b){function k(h,i,d,l){if(L&&"HEAD"===h.tagName){var g=h.parentNode;"HTML"===g.tagName&&(g=g.getElementsByTagName("body"),0<g.length&&(h=g[0]))}var j=a(h,i,d);if(j)return j;for(var g=c(h,e),r=
0;r<g.length;r++)if(j=g[r],j=b.i.b(j))if(j=a(j,i,d))return j;if(H||l)if(l=l||b.i.a(h))if(j=a(l,i,d))return j;return!1}function a(a,i,m){if(!a)return!1;if(null===b.a.b())for(var l=a.getElementsByTagName("embed"),g=0;g<l.length;g++){var j=l[g];if(!("undefined"!==typeof j[t]&&!0===j[t]||-1!=j.id.indexOf("moatPx"))&&j.getAttribute("src")&&3<j.offsetHeight&&3<j.offsetWidth){var e=j.getAttribute("src"),g=b.j.a(e,j);return b.g.a(j,e,!1,g,i,m)}}j=a.getElementsByTagName("object");for(g=0;g<j.length;g++)if(3<
j[g].offsetHeight&&3<j[g].offsetWidth&&(l=j[g],!("undefined"!==typeof l[t]&&!0===l[t]||-1!=l.id.indexOf("moatPx")))){for(g=0;g<l.children.length;g++)if("movie"===l.children[g].name||"Movie"===l.children[g].name){e=l.children[g].value;for(a=0;a<l.children.length;a++){if(null===b.a.b()&&"EMBED"===l.children[a].tagName){j=l.children[a];if("undefined"!==typeof j[t]&&!0===j[t]||-1!=j.id.indexOf("moatPx"))continue;if(3<j.offsetHeight&&3<j.offsetWidth)return g=b.j.a(e,j),b.g.a(j,e,!1,g,i,m)}if("OBJECT"===
l.children[a].tagName)for(j=0;j<l.children[a].children.length;j++){var k=l.children[a].children[j];if("movie"===k.name||"Movie"===k.name)return e=k.value,g=b.j.a(e,l),b.g.a(l.children[a],e,!1,g,i,m)}}}l.object&&l.object.Movie?e=l.object.Movie:l.data&&-1!==l.data.indexOf("swf")&&(e=l.data);g=b.j.a(e,l);return b.g.a(l,e,!1,g,i,m)}e=c(a,d);if(e[0])return b.g.a(e[0],e[0].src,!1,void 0,i,m);e=a.getElementsByTagName("img");for(g=0;g<e.length;g++)if(!("undefined"!==typeof e[g][t]&&!0===e[g][t])){if(2999<
e[g].offsetWidth*e[g].offsetHeight&&""!==e[g].src&&e[g].src!==document.location.href)return b.g.a(e[g],e[g].getAttribute("src"),!1,void 0,i,m);z["1"]=e[g].offsetWidth+"x"+e[g].offsetHeight+":"+e[g].src}return!1}function c(a,c){for(var m=[],l=a.getElementsByTagName("iframe"),g,j=0;j<l.length;j++)if(g=l[j],!g[t]&&3<g.offsetHeight&&3<g.offsetWidth){var k=b.i.b(g)?!1:!0;(c===d&&k||c===e&&!k)&&m.push(g)}return m}b.k={};var d=1,e=2;b.k.a=function(a,c,d,e){var g=k(a,c,d,e),j=0;if(!g)var r=b.c.c(function(){j++;
try{((g=k(a,c,d,e))||9<j)&&clearInterval(r)}catch(b){}},500)}})(n);(function(b){function k(a){var c,d=[],e,h=b.a.a()?2048:7750,i={};e={};for(c in a)a.hasOwnProperty(c)&&("z"===c.slice(0,1)?i[c]=a[c]:1==a.e&&("x"===c||"y"===c||"c"===c)?e[c]=a[c].split("a"):d.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c])));a=d.join("&");c=h-a.length;d=0;if("undefined"!==typeof e.x){for(var m=0,l=0;l<e.x.length;l++)if(m+=e.x[l].length+e.y[l].length+e.c[l].length,m<c)d++;else break;0<d&&(a+="&x="+e.x.slice(0,
d-1).join("a"),a+="&y="+e.y.slice(0,d-1).join("a"),a+="&c="+e.c.slice(0,d-1).join("a"))}for(var g in i)i.hasOwnProperty(g)&&(e="&"+encodeURIComponent(g)+"="+encodeURIComponent(i[g]),e.length+a.length<h&&(a+=e));return a}b.e={};b.e.b=function(a,c){c.startTime=(new Date).getTime();var d={};d.e=a;d.i=A;if(11===a){var e=[],h;for(h in z)z.hasOwnProperty(h)&&e.push(h+"="+z[h]);d.k=e.join("&")}if(!(d.e in M)){d.bq=b.b.b;d.f=Number(!u);d.j=N;d.o=3;d.t=c.startTime;d.m=0;d.ar=O;d.ai="undefined"!==typeof o.z?
o.z:"";d.q=o.m++;d.cb=w?1:0;d.cu=I;if("undefined"!==typeof c){if("undefined"!==typeof c.cid)var i=c.adid+":"+c.cid;d.d=i;"undefined"!==typeof c.clientZone&&(d.bd=c.clientZone)}d.ac=1;d.al=J;d=k(d);o.yh.yi(d+"&cs=0",K,P)}};b.e.a=function(a,c){if(!a||!0===a.KILLED)return!1;if(!b.h.e(a.aa))return b.h.f(a),!1;if(!("undefined"===typeof a.ao||a.ap||2===a.an&&(1===c.e||3===c.e))&&!(c.e in M)){c.ak=a.ae;a.ah&&(c.a=a.ah);var d=a.ag,e;for(e in d)d.hasOwnProperty(e)&&(b.a.a(),""!==e&&"undefined"!==typeof d[e]&&
-1===e.indexOf("dvContains")&&-1===e.indexOf("indexOf")&&(c["z"+e]=d[e]));0!==c.e&&b.h.g(a);a.dy>a.ea&&(a.ea=a.dy);a.dx>a.dz&&(a.dz=a.dx);a.bn>a.ch&&(a.ch=a.bn);a.dq>a.ds&&(a.ds=a.dq);a.bi>a.bg&&(a.bg=a.bi);a.bm>a.bk&&(a.bk=a.bm);c.i=A;c.bq=b.b.b;c.g=a.aq.g++;c.h=0<a.aa.offsetHeight?a.aa.offsetHeight:a.aa.parentNode.offsetHeight;c.f=Number(!u);c.j=N;c.o=3;c.t=a.de;c.cu=I;c.m=c.m||b.a.c(a);c.ar=O;c.w=0<a.aa.offsetWidth?a.aa.offsetWidth:a.aa.parentNode.offsetWidth;c.cb=w?1:0;c.aj=u?a.af:0;c.ag="undefined"!==
typeof a.ch?a.ch:"";c.an="undefined"!==typeof a.bn?a.bn:"";c.bw="undefined"!==typeof a.ds?a.ds:"";c.bx="undefined"!==typeof a.dq?a.dq:"";c.ch=Number(!1);c.ah=a.ea;c.am=a.dy;c.bu=a.dz;c.cd=a.dx;c.ai="undefined"!==typeof o.z?o.z:"";c.ap="undefined"!==typeof a.cb?a.cb:"";c.ax="undefined"!==typeof a.bg?a.bg:"";c.ay="undefined"!==typeof a.bi?a.bi:"";c.az="undefined"!==typeof a.bk?a.bk:"";c.ba="undefined"!==typeof a.bm?a.bm:"";c.aw="undefined"!==typeof a.bc?a.bc:"";c.bg="undefined"!==typeof a.bd?a.bd:"";
c.be="undefined"!==typeof a.be?a.be:"";c.bc="undefined"!==typeof a.bw?a.bw:"";c.bf="undefined"!==typeof a.by?a.by:"";c.bh="undefined"!==typeof a.bx?a.bx:"";c.bz="undefined"!==typeof a.cu?a.cu:"";c.cl=Math.round(100*a.IR5.AREA/(c.w*c.h));c.as=Number(a.cd);c.ck=a.cy||"";c.cc=Number(a.dt);c.ci=a.db||"";c.au=a.aq[2]-1;c.av=a.aq[3]-1;c.by=a.aq[23]-1;c.at=a.dm;if("undefined"!==typeof a.ao.cid)var h=a.ao.adid+":"+a.ao.cid;c.bd=a.ao.clientZone;c.d=h;c.ab=a.an;c.ac=1;c.al=J;c.ca=R;a.dy=a.ea;a.bn=a.ch;a.dq=
a.ds;a.dx=a.dz;a.bi=a.bg;a.bm=a.bk;d=k(c);o.yh.yi(d+"&cs=0",K,P)}};b.e.c=function(a,b){if(!(2===a.an&&(1===b.e||3===b.e))){var d=S;(new Image(1,1)).src=d}};b.e.d=function(a){var c={e:16};c.q=a.aq[16]++;b.e.a(a,c)}})(n);(function(b){function k(a){var b=q,c=b.document.documentElement,d=b.document.body;return"left"===a?b.pageXOffset||c&&c.scrollLeft||d&&d.scrollLeft:b.pageYOffset||c&&c.scrollTop||d&&d.scrollTop}function a(a){for(var c=0,d=0,e,g,j=0;j<y;j++){var k=a.offsetParent;if(k&&k!=a)e=a.offsetLeft||
0,g=a.offsetTop||0,b.b.c&&"TABLE"===a.tagName&&"inline"===a.style.display&&(g=0),c+=e,d+=g,a=k;else break}return{left:c,top:d}}function c(){if("undefined"===typeof o.z){o.z=new Date-I;a:{var a=void 0,d;for(d in p)if(p.hasOwnProperty(d)&&(a=p[d])&&!(a.ap||"undefined"===typeof a.ao)){if(a.ce)break a;var e={e:4};e.q=a.aq[4]++;e.ai=o.z;b.e.a(a,e);a.ce=!0}b.c.b(q,"scroll",c,"onScroll")}}}function d(a,c){var m=b.c.d(function(){var m=c,g={e:9};g.q=a.aq[9]++;b.e.a(a,g);m*=2;m<e&&!1===a.KILLED&&d(a,m)},c);
a.cc=m;a.cw=c}b.h={};var e=18E5;b.h.h=function(){b.c.a(q,"scroll",c,"onScroll");try{"Microsoft Internet Explorer"===navigator.appName?(b.c.a(q.document,"focusout",function(){o.yd()}),b.c.a(q.document,"focusin",function(){o.ye()})):(b.c.a(q,"blur",function(){o.yd()}),b.c.a(q,"focus",function(){o.ye()}))}catch(a){}};b.h.e=function(a,c){try{return c=c||b.h.b(a),a&&a.parentNode&&c}catch(d){return!1}};b.h.g=function(){var a,c,d,e;for(e in p)if(p.hasOwnProperty(e))if(a=p[e],c=a.aa,d=b.h.b(c),b.h.e(c,d)){c=
a;if(b.h.j(c))c.df=+new Date;else{var g=0,j=+new Date,g=j-c.df;c.df=j;w&&1E3<g&&(g=200);c.dz+=g;o.v&&(c.ea+=g)}"undefined"!==typeof a.ao&&u&&(b.h.j(a)?(a.cf=!1,a.cg=0,a.dr=0,a.dg=+new Date):(a.ef=b.h.d(a,d),d=+new Date,c=d-a.dg,a.dg=d,w&&1E3<c&&(c=200),a.ef?a.cf?(o.v&&(a.cg+=c,a.ch+=c),a.dr+=c,a.ds+=c):a.cf=!0:(a.cf=!1,a.cg=0,a.dr=0),o.v||(a.cg=0),1E3<=a.cg&&!a.cd&&u&&(a.cd=!0,a.cy=a.ch,b.h.i(a)),1E3<=a.dr&&!a.dt&&u&&(a.dt=!0,a.db=a.ds,4E3<a.cw&&b.h.i(a))))}else b.h.f(a)};b.h.f=function(a){clearTimeout(a.cc);
a.KILLED=!0;delete p[a.zr]};b.h.d=function(c,d){var e,l,g,j,n=c.aa,s=n.offsetWidth,n=n.offsetHeight;j=q;"undefined"!==typeof j.innerWidth?(g=j.innerWidth,e=j.innerHeight):"undefined"!==typeof j.document.documentElement&&"undefined"!==typeof j.document.documentElement.clientWidth&&0!==j.document.documentElement.clientWidth?(g=j.document.documentElement.clientWidth,e=j.document.documentElement.clientHeight):(g=j.document.getElementsByTagName("body")[0].clientWidth,e=j.document.getElementsByTagName("body")[0].clientHeight);
j=e;var o=c.aa;e=a(o);var p=e.left;l=e.top;c.ee.x=p;c.ee.y=l;if(u&&d&&d!=d.parent)for(var o=b.h.c(o,d),f=0;f<o.length;f++)e=a(o[f]),p+=e.left,l+=e.top;e=p;p=k("top");o=p+j;j=k("left");g+=j;p=Math.max(0,Math.min(p-l,n));l=Math.max(0,Math.min(l+parseInt(n,10)-o,n));l=parseInt(n,10)-p-l;j=Math.max(0,Math.min(j-e,s));g=Math.max(0,Math.min(e+parseInt(s,10)-g,s));g=parseInt(s,10)-j-g;return 0.5<=l*g/(n*s)};b.h.i=function(a){if(!(4E3>=a.cw)){clearTimeout(a.cc);d(a,1E3);var c={e:5};c.q=a.aq[5]++;b.e.a(a,
c)}};b.h.j=function(a){var b=q.document.getElementById("forbes_modal_window");return b&&b.className.match(/\bactive\b/)&&!a.dw};b.h.b=function(a){try{var b=a&&a.ownerDocument;return b&&(b.defaultView||b.parentWindow)}catch(c){return!1}};b.h.c=function(a,c){for(var d=[],e,g=0;g<y;g++)if(c!=c.parent){if(e=b.i.c(a,c))d.push(e);else break;c=c.parent;a=e}else break;return d};b.h.k=function(){for(var a in p)if(p.hasOwnProperty(a)){var c=p[a];if(c){var d={e:21};d.q=c.aq[21]++;b.e.a(c,d)}}};b.h.a=function(a){d(a,
1E3)}})(n);(function(b){function k(a){return a.replace(/^http:/,"").replace(/^\/\//,"").replace(/^www[^.]*\./,"").split("/")[0]}b.i={};b.i.b=function(a){try{if(a.moatHostileIframe)return null;if(a.src&&a.src.slice&&"http"===a.src.slice(0,4)&&k(a.src)!=k(q.location.toString()))return a.moatHostileIframe=!0,null;var b=a&&(a.contentDocument||a.contentWindow&&a.contentWindow.document);if(b&&"string"===typeof b.location.toString())return b;a.moatHostileIframe=!0;return null}catch(d){return a.moatHostileIframe=
!0,null}};b.i.d=function(a){try{var b=typeof a.location.toString,d=typeof a.document;return"undefined"===b||"undefined"===d||"unknown"===b||"unknown"===d}catch(e){return!0}};b.i.c=function(a,c){return(c=c||b.h.b(a))&&c.frameElement};b.i.a=function(a){return(a=b.i.c(a))?a.parentNode:null}})(n);(function(b){b.l={};b.l.a=function(k){k[b.b.a]=k[b.b.a]||{zs:!1,zr:0,h:0,m:0,i:{}};var a=k[b.b.a];"undefined"===typeof a.v&&(a.v=u?"undefined"!==typeof k.document.hasFocus&&!w?k.document.hasFocus():!0:!0);a.ye||
(a.ye=function(){this.v=!0});a.yd||(a.yd=function(){this.v=!1})}})(n);(function(b){function k(b,c,g){b&&d.push({qs:b,jsd:c,fld:g});0===e&&0<d.length&&(e+=1,b=d.shift(),b.fld&&l&&m&&m.sendMessage?m.sendMessage(b):a(b))}function a(b){var d=new g.Image(1,1);d.toSend=b;d.onerror=function(){var b=this.toSend;h+=1;2>h&&a(b)};d.onload=function(){c()};d.src=b.jsd+"/pixel.gif?"+b.qs}function c(){0<e&&(e-=1,k())}var d=[],e=0,h=0,i=(new Date).getTime(),m=!1,l=!1,g;b.m={};b.m.a=function(a){if(!o.yh){o.yh={};
var e=o.yh;g=a;e.yi=function(a,b,c){k(a,b,c)};e.yk=function(a){m=!0;var c=b.b.a+".yh.",d={};d.start=i;d.src="http://js.moatads.com/swf/MessageSenderV2.swf?"+i;d.flashVars="r="+c+"zb&s="+c+"zc&e="+c+"zd&td="+a;return d};e.yj=function(){var a;if(a=!1===m)if(a=!b.a.d())a=(a=/Firefox\/(\d+)/.exec(navigator.userAgent))?14<parseInt(a[1],10):!1,a=!a;return a};e.zb=function(){try{if(!0===m){var a=g.document.getElementById("moatMessageSender"+i);a&&!a.sendMessage&&(a=g.document.getElementById("moatMessageSenderEmbed"+
i));a&&a.sendMessage&&(l=!0,m=a)}}catch(b){}};e.zc=function(){try{c()}catch(a){}};e.zd=function(a){try{l=!1,a&&a.jsd&&d.push(a),c()}catch(b){}}}}})(n);(function(b){function k(a,b){try{return a.exec(b)[1]}catch(d){return"-"}}b.n={};b.n.a=function(a){try{var b=a.className;a.getAttribute("src");var d=b.split("\n").join(" ");if(-1!==b.indexOf("moatfooter"))return!1;var b="undefined",e="",e=a.parentNode.innerHTML,h=/http:\/\/ad.doubleclick.net\/.*?\/.*?\/(.*?);/.exec(e);null!==h&&0<h.length&&(b=h[1]);
var i=k(/moatClientAdvertiserID=(.*?)($| )/,d),m=k(/moatClientOrderID=(.*?)($| )/,d),l=k(/moatClientAdID=(.*?)($| )/,d),g=k(/moatClientCreativeID=(.*?)($| )/,d);return{clientZone:b,clientAdvertiserID:i,clientOrderID:m,clientAdID:l,clientCreativeID:g}}catch(j){return{clientCampaignID:"",clientAdID:""}}};b.n.b=function(a){try{var b=/http:\/\/ad.doubleclick.net\/.*?\/.*?\/(.*?);/.exec(a.innerHTML);0<b.length&&(zone=b[1]);return zone}catch(d){}};b.n.c=function(a){return(a=unescape(unescape(unescape(unescape(a.innerHTML)))).match(/~fdr=(\d*).*?\/.*?;(\d*)/))?
{adid:a&&a[1]||"-",cid:a&&a[2]||"-"}:!1};b.n.d=function(a){var c=a.parentNode,a=unescape(unescape(unescape(unescape(c.innerHTML)))),d=a.match(/\/\*\/[a-z];([^;]*);[^;]*;[^;]*;([0-9]*);[^;]*;([0-9]*)\/([0-9]*)/),c=b.n.b(c);a.search("moatad.js");return d?{adid:d&&d[1]||"-",cid:d&&d[2]||"-",clientZone:c}:!1}})(n);(function(b){b.o={};b.o.a=function(k){if(k&&k.getElementsByTagName)for(var k=k.getElementsByTagName("script"),a=0;a<k.length;a++)try{var c=k[a];if("undefined"!=typeof c.src&&-1!=c.src.indexOf("ad.doubleclick.net")&&
!("undefined"!==typeof c.MOATHEADERCHECKED&&!0===c.MOATHEADERCHECKED)){var d=b.n.d(c);d&&(c.MOATHEADERCHECKED=!0,b.e.b(17,d),b.k.a(c.parentNode,d))}}catch(e){}};b.o.b=function(){b.o.a(document);for(var k=document.getElementsByTagName("iframe"),a=0;a<k.length;a++){var c=k[a];try{if(!("undefined"!==typeof c.MOATHEADERCHECKED&&!0===c.MOATHEADERCHECKED)){var d=b.i.b(c);d&&d.body&&c.parentNode&&b.o.a(d)}}catch(e){}}}})(n);if(n.a.e())return!1;try{var B="http://v3.moatads.com/pixel.gif?e=12&d=data%3Adata%3Adata%3Adata&i="+
escape("FORBESINREDHEADER1")+"&ac=1&k="+escape("")+"&ar="+escape("f03d6f3-clean")+"&j="+escape(document.referrer)+"&cs="+(new Date).getTime();(new Image(1,1)).src=B}catch(T){}var A="FORBESINREDHEADER1",O="f03d6f3-clean",I=+new Date,N=document.referrer,L=window!=window.parent,t="moatFound"+A,v="__moat__"+A,S="",P="v3.moatads.com",K;if(n.a.f())return!1;K="http://v3.moatads.com";var B=n.i.d(window.parent),H=L&&!B,u=B?!1:!n.i.d(window.top),q;q=u?window.top:H?window.parent:window;var J;J=u?q.location.toString().split("?")[0]:
q.document.referrer.split("?")[0];var w=n.a.d(),R=q.document.referrer,G=0,E,F,z={},y=50,x=[],C=[],D=[],p={},M={15:"",12:"",6:"",7:""};n.l.a(q);var o=q[n.b.a];window[n.b.a]=o;n.m.a(q);(function(){G=o.h;o.h++;o.i[G]=!1;!1===o.zs&&(n.h.h(),o.zs=!0);n.c.c(function(){n.h.g()},200);n.c.a(q,"beforeunload",function(){n.h.k()},!1);n.c.c(n.f.b,100);n.a.a()&&n.c.d(Q,3E5);n.o.b();n.c.c(function(){n.o.b()},500)})()})()}catch(e$$27){var msg=e$$27.name+" in closure: "+e$$27.message+", stack="+e$$27.stack;try{var pxSrc=
"http://v3.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("FORBESINREDHEADER1")+"&ac=1&k="+escape(msg)+"&ar="+escape("f03d6f3-clean")+"&j="+escape(document.referrer)+"&cs="+(new Date).getTime(),px=new Image(1,1);px.src=pxSrc}catch(e$$28){}};
