(function(h,g,l){h.SPR||(h.SPR={provide:function(a,d){b[a]||(b[a]=d,"function"===typeof b[a].init&&b[a].init())}});var b=h.SPR;b.provide("Common",{random:function(){return Math.floor(8675309*Math.random())},isArray:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},isString:function(a){return"[object String]"===Object.prototype.toString.call(a)},hasOwnProperty:function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}});b.provide("DOM",{init:function(){function a(){b.DOM.flush();
h.removeEventListener("DOMContentLoaded",a,!1)}function d(){/loaded|interactive|complete/.test(g.readyState)&&(g.detachEvent("onreadystatechange",d),c&&(c=!1,b.DOM.flush()))}b.DOM.on=b.DOM.attachEvent;b.DOM.off=b.DOM.detachEvent;var c=!0;h.addEventListener&&h.addEventListener("DOMContentLoaded",a);g.attachEvent&&g.attachEvent("onreadystatechange",d)},addScript:function(a){var d=g.createElement("script");d.type="text/javascript";d.setAttribute("async",!0);d.setAttribute("name","spr");d.src=a;b.DOM.onReady(function(){setTimeout(function(){b.DOM.$("HEAD")[0].appendChild(d)},
1)});return d},queue:[],ready:/loaded|interactive|complete/.test(g.readyState),flush:function(){var a=b.DOM.queue.shift();for(b.DOM.ready=!0;a;)a(),a=b.DOM.queue.shift()},onReady:function(a){b.DOM.ready?(b.DOM.queue.push(a),b.DOM.flush()):g.documentElement.doScroll?h.self===h.top?function(){if(!g.uniqueID&&g.expando)return b.DOM.queue.push(a);try{g.documentElement.doScroll("left"),a()}catch(d){setTimeout(arguments.callee,0)}}():b.DOM.queue.push(a):b.DOM.queue.push(a)},attachEvent:function(a,b,c){a.addEventListener?
a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},detachEvent:function(a,b,c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},top:function(a){return a?a.y?a.y:a.offsetTop+b.DOM.top(a.offsetParent):0},left:function(a){return a?a.x?a.x:a.offsetLeft+b.DOM.left(a.offsetParent):0},height:function(a){return Math.max(a.scrollHeight||0,a.offsetHeight||0,a.clientHeight||0)},width:function(a){return Math.max(a.scrollWidth||0,a.offsetWidth||0,a.clientWidth||0)},
scroll:function(){var a=0;return a=h.pageYOffset?h.pageYOffset:g.documentElement?g.documentElement.scrollTop:0},viewport:function(){var a=0,d=0,d=g.documentElement;if(h.innerWidth)a=h.innerWidth,d=h.innerHeight;else{if(!d||!d.clientWidth)d=b.$("BODY")[0];a=d.clientWidth;d=d.clientHeight}return{w:a,h:d}},getsupportedprop:function(a){for(var b=g.documentElement,c=0;c<a.length;c++)if("string"==typeof b.style[a[c]])return a[c]},$:function(a){var b=[],c,e=0,f;if(!a)return[];if("string"!==typeof a)return[a];
switch(a.charAt(0)){case "#":b.push(g.getElementById(a.substring(1)));break;case ".":c=g.getElementsByTagName("*");for(f=" "+a.substring(1)+" ";e<c.length;e+=1)a=(" "+c[e].className+" ").replace(/[\n\t\r]/g," "),-1<a.indexOf(f)&&b.push(c[e]);break;default:b=g.getElementsByTagName(a)}return b}});b.provide("QS",{escape:function(a){return encodeURIComponent(a)},unescape:function(a){return decodeURIComponent(a)},encode:function(a,d){var c=b.QS,e=[];if(b.Common.isArray(a))for(var f=0,i;f<a.length;f+=1)i=
a[f],/\[\]$/.test(d)?e.push(c.escape(d)+"="+c.escape(i)):e.push(c.encode(i,d+"["+("object"===typeof i?f:"")+"]"));else if("object"===typeof a&&null!==a&&!("nodeType"in a))for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&(d?e.push(c.encode(a[f],d+"["+f+"]")):e.push(c.encode(a[f],f)));else e.push(c.escape(d)+"="+c.escape(a));return e.join("&")},decode:function(a){for(var d={},c=0,e={"true":!0,"false":!1,"null":null},a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var f=a[c].split("="),i=b.QS.unescape(f[0]),
j=d,k=0,g=i.split("]["),h=g.length-1;/\[/.test(g[0])&&/\]$/.test(g[h])?(g[h]=g[h].replace(/\]$/,""),g=g.shift().split("[").concat(g),h=g.length-1):h=0;if(2===f.length)if(f=(f=b.QS.unescape(f[1]))&&!isNaN(f)?+f:"undefined"===f?void 0:void 0!==e[f]?e[f]:f,h)for(;k<=h;k+=1)i=""===g[k]?j.length:g[k],j=j[i]=k<h?j[i]||(g[k+1]&&isNaN(g[k+1])?{}:[]):f;else b.Common.isArray(d[i])?d[i].push(f):d[i]=void 0!==d[i]?[d[i],f]:f;else i&&(d[i]=void 0)}return d}});b.provide("API",{callbacks:{},jsonp:function(a,d,c,
e,f){e=e||l;f||(f="cb");var i="cb"+b.Common.random(),j=b.API;c[f]="SPR.API.callbacks."+i;f=g.location.protocol+"//";"file://"===f&&(f="http://");var c=b.QS.encode(c),h=b.DOM.addScript(f+a+d+"?"+c);j.callbacks[i]=function(a){setTimeout(function(){h.parentNode.removeChild(h)},0);e(a);try{delete j.callbacks[i]}catch(b){j.callbacks[i]=null}}}});b.provide("de",{api:"feeds.delicious.com",apiPath:"/v2/json/urlinfo/data",collect:function(a){var d=b.de;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com",
"/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"de",data:c})},"callback")}});b.provide("dg",{api:"services.digg.com",apiPath:"/stories/",collect:function(a){var d=b.dg;b.API.jsonp(d.api,d.apiPath,{type:"javascript",link:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"dg",data:c})},"callback")}});b.provide("fb",{api:"graph.facebook.com",apiPath:"/fql",collect:function(a){var d=b.fb;b.API.jsonp(d.api,d.apiPath,{q:'SELECT url,total_count,share_count,comment_count,like_count,click_count,commentsbox_count FROM link_stat WHERE url in ("'+
a.url+'")'},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"fb",data:c})},"callback")}});b.provide("gp",{api:"clients6.google.com",apiPath:"rpc",collect:function(){}});b.provide("li",{api:"www.linkedin.com",apiPath:"/countserv/count/share",collect:function(a){var d=b.li;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"li",data:c})},"callback")}});b.provide("rd",
{api:"www.reddit.com",apiPath:"/api/info.json",collect:function(a){var d=b.rd;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"rd",data:c})},"jsonp")}});b.provide("pi",{api:"partners-api.pinterest.com",apiPath:"/v1/urls/count.json",collect:function(a){var d=b.pi;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"pi",data:c})},
"callback")}});b.provide("su",{api:"www.stumbleupon.com",apiPath:"/services/1.01/badge.getinfo",collect:function(a){var d=b.su;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"su",data:c})})}});b.provide("tw",{api:"urls.api.twitter.com",apiPath:"/1/urls/count.json",collect:function(a){var d=b.tw;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,
cid:a.id,pid:a.pid,sn:"tw",data:c})},"callback")}});b.provide("Reach",{api:"cc.simplereach.com",cdn:"d8rk54i4mohrb.cloudfront.net",config:{},init:function(){if(h.location.host!==b.Reach.cdn)try{var a=b.Reach,d=h.__reach_config||h.__spr_config,c=a.config||{},e;for(e in d)void 0===c[e]&&(c[e]=d[e]);c.ckw&&(c.tags=c.ckw.split(" "));c.pub&&(c.date=c.pub);c.cat&&(c.channels=c.cat.split(" "));if(!0===c.no_slide||1===c.no_slide)c.slide_active=!1;a.config=c;a.collect(c)}catch(f){b.DOM.onReady(function(){var a=
g.createElement("img");a.src="http://cc.simplereach.com/pixel?bad=true&error="+f.message;a.setAttribute("width","1px");g.body.appendChild(a)})}},collect:function(a){function d(a){"string"===typeof a&&(a=a.split(","));if(b.Common.isArray(a)){for(var c=0;c<a.length;c+=1)"string"===typeof a[c]&&(a[c]=a[c].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}return a}var c=b.Reach,e={};e.pid=a.pid;e.url=a.url;e.title=a.title;e.date=a.date;e.domain=a.domain;e.ref_url=a.ref_url;e.referrer=
g.referrer;a.authors&&(e.authors=d(a.authors));a.channels&&(e.channels=d(a.channels));a.tags&&(e.tags=d(a.tags));a.date&&"string"!==typeof a.date&&(e.date=a.date.toString());if(!e.pid||!e.url||!e.date){if(!a.ignore_errors)try{console.log("SPR-ERROR: Please provide pid, url and date in the configuration")}catch(f){}}else{if(0===e.url.indexOf("http%3"))try{e.url=decodeURIComponent(e.url)}catch(h){e.url=unescape(e.url)}a.url=e.url;b.API.jsonp(c.api,"/n",e,function(a){if(!1!==a.slide){var d=!1;!0===c.config.slide_active?
d=!0:!1!==c.config.slide_active&&!0===a.slide&&(d=!0);b.Slide&&(!0===d&&!1===b.Slide.enabled)&&b.Slide.enable(a.id)}a.de&&b.de.collect(a);a.dg&&b.dg.collect(a);a.fb&&b.fb.collect(a);a.gp&&b.gp.collect(a);a.li&&b.li.collect(a);a.rd&&b.rd.collect(a);a.su&&b.su.collect(a);a.tw&&b.tw.collect(a);a.pi&&b.pi.collect(a)})}}})})(window,document,function(){});
